language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.7.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.3.*'
    - php: 7.1
      env: DEPENDENCIES='dev' SYMFONY_VERSION='3.4.*@dev'
    - php: 7.1
      env: DEPENDENCIES='dev' SYMFONY_VERSION='4.0.*'
  fast_finish: true

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 5.* ]]; then pecl install dbase; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then pecl install dbase-7.0.0beta1; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer install --dev

script: vendor/bin/phpunit